config:
  target: 'https://lemonade.leersteun.lars-tst.school'
  processor: "../../utils/response-logger.js"
  phases:
    - duration: 1
      arrivalRate: 1
      name: "Care reception load"
  environments:
    tst:
      target: 'https://lemonade.leersteun.lars-tst.school'
      phases:
        - duration: 1
          arrivalRate: 1
      variables:
        learning_support_center_id_: "4126aba9-622d-4ada-98c3-2eb319793ec6"    
      payload:
        path: '../../data/acc-learning-support-centers.csv'
        fields:
          - 'learning_support_center_id'
          - 'name'
          - 'access_token' 
          - 'mongo_claims'
        skipHeader: true
        delimiter: ','  
    acc:
      target: 'https://lemonade.leersteun.lars-acc.school'
      phases:
        - duration: 1
          arrivalRate: 1
      payload:
        path: '../../data/acc-learning-support-centers.csv'
        fields:
          - 'learning_support_center_id'
          - 'name'
          - 'access_token' 
          - 'mongo_claims'
        skipHeader: true
        delimiter: ','
    prd:
      target: 'https://leersteun.lars.school'
      phases:
        - duration: '1s'
          arrivalRate: 4
          maxVusers: 5000
        # - duration: '5m'
        #   arrivalRate: 10
        #   rampTo: 50  
      payload:
        path: '../../data/prd-learning-support-centers.csv'
        fields:
          - 'learning_support_center_id'
          - 'name'
          - 'access_token' 
          - 'mongo_claims'
        skipHeader: true
        delimiter: ','