# This is a basic workflow to help you get started with Actions

name: Run Artillery tests in parallel using a matrix

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Create a scenario_name variable in this job that will be used to
        # run an Artillery test for that scenario
        scenario_name:
          - support-questions/queries/care_reception
          - teams/queries/teams
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          scenario_name: ${{ matrix.scenario_name }}

      - name: Install Artillery
        run: npm install -g artillery

      - name: Run Artillery tests in parallel
        run: |
          artillery run -e prd artillery/${{matrix.scenario_name}}.yml --config artillery/config/config_lists.yml